### ISSUE TITLE
Compatibility with storybook 3

### ISSUE THREAD

**Issue by Ilaiwi** [hydrateio/docz-plugin-storybook#33]
First, thank you so much for the great plugin! 

I am trying to run this plugin with storybook 3 but unfortunately, keep getting an error 

```
{ Error: Cannot find module '@storybook/react/standalone'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\AhmadIlaiwi\foothill\Docz\node_modules\docz-plugin-storybook\src\build-storybook.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Module._compile (C:\Users\AhmadIlaiwi\foothill\Docz\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Object.newLoader [as .js] (C:\Users\AhmadIlaiwi\foothill\Docz\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\AhmadIlaiwi\foothill\Docz\node_modules\docz-plugin-storybook\src\index.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30) code: 'MODULE_NOT_FOUND' }
There was an error loading your config:
```

From what I understood the standalone package is only in storybook 4. I tried to run also your example for react-vis since it is running storybook 3 but no luck as well.

My question is: is it compatible with stroybook 3 or not? if yes maybe you can help me run the example locally for `react-vis`?

**Comment by jpeters5392** [comment]
@Ilaiwi thank you for trying out our plugin.  It does support SB3, although how well it supports it also depends on the version of docz that you are using.  There can be issues with the Babel/Webpack dependencies since both of them require different versions, and in some cases those versions might be incompatible.  However, I did find the issues that were preventing the react-vis example from working so if you pull down the latest code and/or try 0.5.1 of the plugin then hopefully it should work for you now.

**Comment by Ilaiwi** [comment]
@jpeters5392  thank you for the fast response. Any ideas about the error though?

**Comment by jpeters5392** [comment]
@Ilaiwi I didn't run into that error when I tried building the `react-vis` example.  I did run into other errors about `babel-loader` and the plugin wasn't able to scrape the stories from Storybook, so those are fixed.  What version of Storybook and docz are you using in your project?

**Comment by Ilaiwi** [comment]
@jpeters5392  We run a sub-modules setup so the react and storybook source file is in a child directory of my docz root project. I did configure my `.storybook` the path via the config param on the plugin...

as for the versions, I run docz@1.2.0 and storybook@3.4

**Comment by jpeters5392** [comment]
@Ilaiwi What happens if you try the `react-vis` example now?  Does that work for you?  I'm not sure what the error is that you are seeing, since the `react-vis` example uses SB 3.4.11 and is working for me.

Which package.json includes your storybook dependency, the parent docz folder or the submodule?

**Comment by Ilaiwi** [comment]
@jpeters5392 yes it is working now for me

the dependencies are in the parent directory

**Comment by jpeters5392** [comment]
I'll have to look into why you might be getting that error when the example
isn't.  In the meantime there is a workaround that you can do.  It is
possible to pass in a list of stories to the plugin and that will cause it
to skip the Storybook scraping and render those stories in docz.  I will
have to dig up the format for that.  Generally that approach is better
since it will be faster since it won't have to spin up Storybook internally.

**Comment by jpeters5392** [comment]
Here is the format for the JSON file.  I included 2 of the story kinds from the `react-vis` example.  In your `.doczrc` file you would pass this in like the following.  Going this route will let you at least try it out and see how it will render.  There are also some hooks available for you to completely customize the generated MDX files if you want them to look different.

`
const { storybook } = require('docz-plugin-storybook')
const { createPlugin } = require('docz-core')
const stories = require('./stories.json')

module.exports = {
  wrapper: undefined,
  indexHtml: null,
  plugins: [
    storybook(createPlugin, { stories })
  ]
}
`

`
[
  {
    "kind": "Series/AreaSeries/Base",
    "fileName": "./storybook/areaseries-story.js",
    "stories": [
      {
        "name": "Single Area chart",
        "parameters": {
          "fileName": "./storybook/areaseries-story.js"
        }
      },
      {
        "name": "Single Area chart paired with LineSeries",
        "parameters": {
          "fileName": "./storybook/areaseries-story.js"
        }
      },
      {
        "name": "With negative numbers",
        "parameters": {
          "fileName": "./storybook/areaseries-story.js"
        }
      },
      {
        "name": "With non-uniform x numbers",
        "parameters": {
          "fileName": "./storybook/areaseries-story.js"
        }
      },
      {
        "name": "Multiple Area series",
        "parameters": {
          "fileName": "./storybook/areaseries-story.js"
        }
      },
      {
        "name": "Multiple stacked Area series",
        "parameters": {
          "fileName": "./storybook/areaseries-story.js"
        }
      }
    ]
  },
  {
    "kind": "Series/AreaSeries/Styling",
    "fileName": "./storybook/areaseries-story.js",
    "stories": [
      {
        "name": "opacity",
        "parameters": {
          "fileName": "./storybook/areaseries-story.js"
        }
      },
      {
        "name": "stroke",
        "parameters": {
          "fileName": "./storybook/areaseries-story.js"
        }
      },
      {
        "name": "style object",
        "parameters": {
          "fileName": "./storybook/areaseries-story.js"
        }
      }
    ]
  }
]
`

**Comment by Ilaiwi** [comment]
@jpeters5392 So I've been able to reproduce the error I am getting using the react-vis example. So apparently @storybook/react/standalone is part of storybook@4 and not storybook@3. your example works because you use @storybook/react@4 in your root package.json
https://github.com/hydrateio/docz-plugin-storybook/blob/master/package.json#L63

So by deleting this dependency and trying to run the `react-vis` example it would show the same error I am getting.

I can provide a reproduce repo if you see that my reproduce steps are not clear.

```
Error: Cannot find module '@storybook/react/standalone'
    at Object.<anonymous> (/Users/ahmadilaiwi/Documents/foothill/docz-plugin-storybook/dist/build-storybook.js:13:42)
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10) code: 'MODULE_NOT_FOUND' }
```

**Comment by jpeters5392** [comment]
Interesting, I will take a look at that.  I did remove the yarn link and
pull in the plugin via yarn and verify the lock file only mentioned SB 3.4,
and the Storybook in the node_modules folder was SB 3.4, so it must have
been pulling it in from the parent folder.  I'll see if it will be simple
to make that backwards compatible, otherwise we might not be able to
support SB 3.

In the meantime, you should be able to use that stories file format that I
mentioned to see how it will look once it does start working.

**Comment by Ilaiwi** [comment]
@jpeters5392 I cant compile my project with this error unfortunately

**Comment by jpeters5392** [comment]
Ok, I will see if I can make a quick change so that the import for that is
conditional.

**Comment by jpeters5392** [comment]
@Ilaiwi Go ahead and pull down 0.5.2.  It will require you to pass in the stories if you are running SB3 but it will no longer blow up due to that missing package.  We will try to get SB3 story scraping added back in at some point.

**Comment by Ilaiwi** [comment]
@jpeters5392 thank you :D I will try it and let you know
